In [79]:
import numpy as np
import scipy as sp
import sympy as sym

In [80]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=np.float32)

print(A)
print(np.linalg.matrix_rank(A))
print(A.shape[1] - np.linalg.matrix_rank(A))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2
1


In [82]:
print(l := sp.linalg.lu(A, permute_l=True)[0])
print()
print(u := sp.linalg.lu(A, permute_l=True)[1])
print()
print(l @ u)

[[0.14285715 1.         0.        ]
 [0.5714286  0.4999998  1.        ]
 [1.         0.         0.        ]]

[[7.        8.        9.       ]
 [0.        0.8571428 1.7142856]
 [0.        0.        0.       ]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [84]:
sym.Matrix(A).rref()[0]

Matrix([
[1, 0, -1.0],
[0, 1,  2.0],
[0, 0,    0]])

In [75]:
sym.Matrix(A).columnspace()[0]

Matrix([
[1.0],
[4.0],
[7.0]])

In [76]:
sym.Matrix(A).columnspace()[1]

Matrix([
[2.0],
[5.0],
[8.0]])

In [77]:
sym.Matrix(A).nullspace()[0]

Matrix([
[ 1.0],
[-2.0],
[   1]])